export const cities = [
  "Abu Road, Rajasthan",
  "Ahmedabad, Gujarat",
  "Amritsar, Punjab",
  "Ayodhya, Uttar Pradesh",
  "Bengaluru, Karnataka",
  "Bhatinda, Punjab",
  "Chennai, Tamil Nadu",
  "Coimbatore, Tamil Nadu",
  "Dehradun / Massourie, Uttarakhand",
  "Delhi NCR, Delhi",
  "Dharmshala, Himachal Pradesh",
  "Goa, Goa",
  "Guwahati, Assam",
  "Hyderabad, Telangana",
  "Indore, Madhya Pradesh",
  "Jaipur, Rajasthan",
  "Jammu, Jammu and Kashmir",
  "Jamshedpur, Jharkhand",
  "Kochi, Kerala",
  "Kolkata, West Bengal",
  "Lucknow, Uttar Pradesh",
  "Mahableswar, Maharashtra",
  "Manali, Himachal Pradesh",
  "Mohali, Punjab",
  "Mumbai, Maharashtra",
  "Mysore, Karnataka",
  "Nagpur, Maharashtra",
  "Nainital/ Mukhteshwar, Uttarakhand",
  "Nasik, Maharashtra",
  "Palampur, Himachal Pradesh",
  "Patiala / Ludhiana, Punjab",
  "Patna, Bihar",
  "Prayagraj, Uttar Pradesh",
  "Pune, Maharashtra",
  "Puri, Odisha",
  "Raipur, Chhattisgarh",
  "Rajkot, Gujarat",
  "Rampur, Uttar Pradesh",
  "Ranchi, Jharkhand",
  "Somnath, Gujarat",
  "Surat, Gujarat",
  "Trivandrum, Kerala",
  "Udaipur, Rajasthan",
  "Ujjain, Madhya Pradesh",
  "Varanasi, Uttar Pradesh",
  "Vijayawada, Andhra Pradesh",
  "Vishakhapatnam, Andhra Pradesh",
  "Vrindavan, Uttar Pradesh",
  "Yamunagar, Haryana"
];
