export const data = [
  {
    order1: `md:order-1 order-1`,
    order2: `md:order-2 order-2`,
    dis: `Round-the-clock nursing care, on-call doctors, emergency response, and regular health check-ups ensure your well-being is never compromised. We’re also partnered with leading multispecialty hospitals for seamless emergency admissions when needed.`,
    cont1: "Healthcare — 24/7 Peace of Mind",
    head: "02",
    img: "/lifeAt/lifrat3.jpg",
  },
  {
    order1: `md:order-2 order-1`,
    order2: `md:order-1 order-2`,
    dis: `Enjoy a spotless, stress-free home with flexible housekeeping services that fit your routine. From daily cleaning to deep sanitization, our team ensures your space stays as welcoming as you are.`,
    cont1: "Housekeeping — Your Comfort, Our Priority",
    head: "03",
    img: "/lifeAt/lifrat4.jpg",
  },
  {
    order1: `md:order-1 order-1`,
    order2: `md:order-2 order-2`,
    dis: `Need a doctor’s appointment? A dinner reservation? A travel booking? Our concierge team is just a call away, managing your everyday tasks so you can live worry-free. We also plan and arrange senior-friendly travel.`,
    cont1: "Concierge — Help When You Need It",
    head: "04",
    img: "/lifeAt/lifrat5.jpg",
  },
  {
    order1: `md:order-2 order-1`,
    order2: `md:order-1 order-2`,
    dis: `From yoga and fitness sessions to music, art, and cultural events, we offer an ever-evolving calendar of programs to keep you moving, learning, and connecting with others in the community.`,
    cont1: "Activities — Stay Active, Engaged, and Inspired",
    head: "05",
    img: "/lifeAt/lifrat6.jpg",
  },
  {
    order1: `md:order-1 order-1`,
    order2: `md:order-2 order-2`,
    dis: `Beautifully landscaped gardens and walking trails invite you to connect with nature. We believe the outdoors plays a vital role in enhancing physical health and emotional balance, especially as we grow older.`,
    cont1: "Outdoor Living — Breathe, Walk, Reflect",
    head: "06",
    img: "/lifeAt/lifrat7.jpg",
  },
  {
    order1: `md:order-2 order-1`,
    order2: `md:order-1 order-2`,
    dis: `Library lounges, wellness zones, indoor games, clubs, and more—our recreational spaces are designed to help you unwind, recharge, and grow in a vibrant, supportive environment. These spaces allow you to live life the way have been living.`,
    cont1: "Recreational Spaces — Relax and Rejuvenate",
    head: "08",
    img: "/lifeAt/lifrat8.jpg",
  },
];
