export const data = [
  {
    image: "/propertyImage.jpg",
    city: "Goa",
    title: "ParadisePoint Villa",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/housing1.jpg",
    title: "Varanasi",
    city: "Varanasi",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/housing2.jpg",
    title: "ParadisePoint Villa",
    city: "Jalandhar",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/housing3.jpg",
    title: "ParadisePoint Villa",
    city: "Ayodhya",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/Indore.jpg",
    title: "ParadisePoint Villa",
    city: "Indore",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/Mathura.jpg",
    title: "ParadisePoint Villa",
    city: "Mathura/Vrindavan",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/Mumbai.jpg",
    title: "ParadisePoint Villa",
    city: "Mumbai",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
];
