export const data = [
  {
    image: "/propertyImage.jpg",
    city: "Goa",
    title: "ParadisePoint Villa",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/propertyImage.jpg",
    title: "ParadisePoint Villa",
    city: "Pune",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/propertyImage.jpg",
    title: "ParadisePoint Villa",
    city: "Amritsar ",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/propertyImage.jpg",
    title: "ParadisePoint Villa",
    city: "Ahmedabad ",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/propertyImage.jpg",
    title: "ParadisePoint Villa",
    city: "Chennai",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
];
