export const data = [
  {
    image: "/properties/propertyImage.webp",
    city: "Goa",
    title: "ParadisePoint Villa",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/properties/housing1.webp",
    title: "Varanasi",
    city: "Varanasi",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/properties/housing2.webp",
    title: "ParadisePoint Villa",
    city: "Jalandhar",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/properties/housing3.webp",
    title: "ParadisePoint Villa",
    city: "Ayodhya",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/properties/housing5.webp",
    title: "ParadisePoint Villa",
    city: "Indore",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/properties/Mathura.webp",
    title: "ParadisePoint Villa",
    city: "Mathura/Vrindavan",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
  {
    image: "/properties/Mumbai.webp",
    title: "ParadisePoint Villa",
    city: "Mumbai",
    beds: 4,
    baths: 3,
    area: 230,
    parking: 2,
    location: "550 Hudson Hills",
    price: 5999,
  },
];
